// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pre_Trainee_Task.Data;

#nullable disable

namespace Pre_Trainee_Task.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    [Migration("20250806095352_ModelAttributes")]
    partial class ModelAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Pre_Trainee_Task.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14ea5e54-ac6a-48ce-89c8-bffe04843b40"),
                            CreatedAt = new DateTime(2025, 8, 6, 9, 53, 51, 421, DateTimeKind.Utc).AddTicks(5123),
                            Message = "Bug description message",
                            Status = 0,
                            Title = "Bug Title",
                            Type = 0,
                            UserId = new Guid("6a1d338f-8a9a-43c7-bb79-6fbe9f6d82d9")
                        },
                        new
                        {
                            Id = new Guid("4fc0f104-9587-48ee-ac9e-0521458f59dd"),
                            CreatedAt = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Message = "Suggestion description message",
                            Status = 1,
                            Title = "Suggestion Title",
                            Type = 1,
                            UserId = new Guid("947ee152-6f9b-481f-87cf-50fcc89e9072")
                        },
                        new
                        {
                            Id = new Guid("17b19f7b-85d7-4f0a-8df0-7cefbde94e2d"),
                            CreatedAt = new DateTime(2025, 7, 30, 9, 53, 51, 421, DateTimeKind.Utc).AddTicks(5438),
                            Message = "Question message",
                            Status = 2,
                            Title = "Question Title",
                            Type = 2,
                            UserId = new Guid("5c166b8f-e264-427c-8eff-d68664a6eacc")
                        });
                });

            modelBuilder.Entity("Pre_Trainee_Task.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfbc0d4a-83ec-4d10-9170-e2dad71bfa2a"),
                            Email = "admin@admin.com",
                            PasswordHash = "$2a$11$T/pSyXQjLDIHE2ts56gAlOnD3iYpHgBwHid5tiiHAA2EuBkN02Urq",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("fc521106-c115-4152-bcf2-7a7044e90e94"),
                            Email = "user@user.com",
                            PasswordHash = "$2a$11$gFry0rbXS.HytKr7SGpbcuOQh3rWQ2/LMLHmnIUFZbgC8ltWcmynm",
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
