// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pre_Trainee_Task.Data;

#nullable disable

namespace Pre_Trainee_Task.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    [Migration("20250805101113_AddedUsers")]
    partial class AddedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Pre_Trainee_Task.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be8743a9-b2b0-4168-9877-987dab1c2f25"),
                            CreatedAt = new DateTime(2025, 8, 5, 10, 11, 12, 721, DateTimeKind.Utc).AddTicks(6132),
                            Message = "Bug description message",
                            Status = 0,
                            Title = "Bug Title",
                            Type = 0,
                            UserId = new Guid("87c013e7-726a-4a7c-ab6e-67b04ab54923")
                        },
                        new
                        {
                            Id = new Guid("5c3a8ae3-26cd-46a4-be27-b292891c5557"),
                            CreatedAt = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Message = "Suggestion description message",
                            Status = 1,
                            Title = "Suggestion Title",
                            Type = 1,
                            UserId = new Guid("f0a01a8c-67fe-4e97-9891-14534d75f185")
                        },
                        new
                        {
                            Id = new Guid("ffb38de6-255f-486f-9f4f-8c6a6080279d"),
                            CreatedAt = new DateTime(2025, 7, 29, 10, 11, 12, 721, DateTimeKind.Utc).AddTicks(6648),
                            Message = "Question message",
                            Status = 2,
                            Title = "Question Title",
                            Type = 2,
                            UserId = new Guid("56a3ae7d-2aa4-45ca-a5ad-c7b8f4723d82")
                        });
                });

            modelBuilder.Entity("Pre_Trainee_Task.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
