// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pre_Trainee_Task.Data;

#nullable disable

namespace Pre_Trainee_Task.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    [Migration("20250805072604_TestDataMigration")]
    partial class TestDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Pre_Trainee_Task.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0be68ac3-77fe-4a0e-ba2b-9d0a7f9cf998"),
                            CreatedAt = new DateTime(2025, 8, 5, 7, 26, 3, 559, DateTimeKind.Utc).AddTicks(993),
                            Message = "Bug description message",
                            Status = 0,
                            Title = "Bug Title",
                            Type = 0,
                            UserId = new Guid("469d286f-0edb-4723-bf64-70db4a19d2c4")
                        },
                        new
                        {
                            Id = new Guid("7fdfda00-6ceb-45ab-ad98-42105d839688"),
                            CreatedAt = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Message = "Suggestion description message",
                            Status = 1,
                            Title = "Suggestion Title",
                            Type = 1,
                            UserId = new Guid("1f691bb7-9228-4584-925d-49defd56e48c")
                        },
                        new
                        {
                            Id = new Guid("807561cc-9a9f-4205-a850-70f8095a0837"),
                            CreatedAt = new DateTime(2025, 7, 29, 9, 26, 3, 559, DateTimeKind.Local).AddTicks(1217),
                            Message = "Question message",
                            Status = 2,
                            Title = "Question Title",
                            Type = 2,
                            UserId = new Guid("1429e2d3-b0d2-4591-9468-91301173a6e7")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
