// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pre_Trainee_Task.Data;

#nullable disable

namespace Pre_Trainee_Task.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    [Migration("20250805122537_TestUsers")]
    partial class TestUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Pre_Trainee_Task.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99ef5e49-a788-4d32-baf7-831547582a00"),
                            CreatedAt = new DateTime(2025, 8, 5, 12, 25, 37, 294, DateTimeKind.Utc).AddTicks(707),
                            Message = "Bug description message",
                            Status = 0,
                            Title = "Bug Title",
                            Type = 0,
                            UserId = new Guid("3d3f62d1-2fbf-487a-b46d-5f74b5162c66")
                        },
                        new
                        {
                            Id = new Guid("25358b8d-d761-4b16-93ca-2786c9438ac5"),
                            CreatedAt = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Message = "Suggestion description message",
                            Status = 1,
                            Title = "Suggestion Title",
                            Type = 1,
                            UserId = new Guid("e8ceaad0-68aa-44c4-a037-6ad88e5d5483")
                        },
                        new
                        {
                            Id = new Guid("f30c7cea-7ce9-4ea5-8d07-1183af05332c"),
                            CreatedAt = new DateTime(2025, 7, 29, 12, 25, 37, 294, DateTimeKind.Utc).AddTicks(1032),
                            Message = "Question message",
                            Status = 2,
                            Title = "Question Title",
                            Type = 2,
                            UserId = new Guid("13d7cc02-3b5d-4a3e-b711-9e226479fa20")
                        });
                });

            modelBuilder.Entity("Pre_Trainee_Task.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e63979ec-e7cc-4be6-a6e6-201008979a29"),
                            Email = "admin@admin.com",
                            PasswordHash = "$2a$11$XaZwPNX.YZ300ZXQuVDp6.vvPJXRhaxWdmv1HM1C/.bugtEJe45Om",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0252de01-d95a-470b-b00a-17ffbb5bce78"),
                            Email = "user@user.com",
                            PasswordHash = "$2a$11$VpPm1lXoGx7Y6O0qoF97D.Kw/xFPZ5V79n9mKPTcip3QM/a9.4TTO",
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
